### ISSUE TITLE
Installing zim-tools fails on Ubuntu Server 20.04.2 -- partial workaround is to download mustache.hpp into /usr/include

### ISSUE THREAD

**Issue by holta** [openzim/zim-tools#242]
Summary: zim-tools install instructions at https://github.com/openzim/zim-tools#compilation do not work on Ubuntu Server 20.04.2

_Thanks if anybody has suggestions for PROBLEM 2 OF 2 below!_

### PROBLEM 1 OF 2:

```
git clone https://github.com/openzim/zim-tools
cd zim-tools
meson . build
```

...can be solved with this workaround: (thanks to @curtathompson and @georgejhunt)

```
cd /usr/include
wget https://raw.githubusercontent.com/kainjow/Mustache/master/mustache.hpp
cd /opt/iiab/zim-tools
meson . build
```

Error Log 1: (output of `meson . build`)
https://paste.ubuntu.com/p/wZkcfSHsTm/

Error Log 2: (/opt/iiab/zim-tools/build/meson-logs/meson-log.txt)
https://paste.ubuntu.com/p/HK45rXKqFS/

### PROBLEM 2 OF 2: (this is the output of `ninja -C build`)

```
ninja: Entering directory `build'
[2/22] Compiling C++ object 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o'.
FAILED: src/25a6634@@zimsearch@exe/zimsearch.cpp.o
c++ -Isrc/25a6634@@zimsearch@exe -Isrc -I../src -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++11 -g -Werror -Wall '-DVERSION="2.2.0"' -MD -MQ 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o' -MF 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o.d' -o 'src/25a6634@@zimsearch@exe/zimsearch.cpp.o' -c ../src/zimsearch.cpp
../src/zimsearch.cpp: In function ‘void printSearchResults(zim::Search&)’:
../src/zimsearch.cpp:28:23: error: ‘iterator’ is not a member of ‘zim::Search’
   28 |     for (zim::Search::iterator it = search.begin(); it != search.end(); ++it)
      |                       ^~~~~~~~
../src/zimsearch.cpp:28:53: error: ‘it’ was not declared in this scope; did you mean ‘int’?
   28 |     for (zim::Search::iterator it = search.begin(); it != search.end(); ++it)
      |                                                     ^~
      |                                                     int
../src/zimsearch.cpp:28:66: error: ‘class zim::Search’ has no member named ‘end’
   28 |     for (zim::Search::iterator it = search.begin(); it != search.end(); ++it)
      |                                                                  ^~~
../src/zimsearch.cpp: In function ‘int main(int, char**)’:
../src/zimsearch.cpp:65:34: error: no matching function for call to ‘zim::Search::Search(zim::Archive&)’
   65 |     zim::Search search(zimarchive);
      |                                  ^
In file included from ../src/zimsearch.cpp:21:
/usr/local/include/zim/search.h:182:9: note: candidate: ‘zim::Search::Search(std::shared_ptr<zim::InternalDataBase>, const zim::Query&)’
  182 |         Search(std::shared_ptr<InternalDataBase> p_internalDb, const Query& query);
      |         ^~~~~~
/usr/local/include/zim/search.h:182:9: note:   candidate expects 2 arguments, 1 provided
/usr/local/include/zim/search.h:162:9: note: candidate: ‘zim::Search::Search(zim::Search&&)’
  162 |         Search(Search&& s);
      |         ^~~~~~
/usr/local/include/zim/search.h:162:25: note:   no known conversion for argument 1 from ‘zim::Archive’ to ‘zim::Search&&’
  162 |         Search(Search&& s);
      |                ~~~~~~~~~^
../src/zimsearch.cpp:66:12: error: ‘class zim::Search’ has no member named ‘set_query’; did you mean ‘zim::Query zim::Search::m_query’? (not accessible from this context)
   66 |     search.set_query(s);
      |            ^~~~~~~~~
In file included from ../src/zimsearch.cpp:21:
/usr/local/include/zim/search.h:188:16: note: declared private here
  188 |          Query m_query;
      |                ^~~~~~~
[3/22] Compiling C++ object 'src/25a6634@@zimpatch@exe/zimpatch.cpp.o'.
FAILED: src/25a6634@@zimpatch@exe/zimpatch.cpp.o
c++ -Isrc/25a6634@@zimpatch@exe -Isrc -I../src -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++11 -g -Werror -Wall '-DVERSION="2.2.0"' -MD -MQ 'src/25a6634@@zimpatch@exe/zimpatch.cpp.o' -MF 'src/25a6634@@zimpatch@exe/zimpatch.cpp.o.d' -o 'src/25a6634@@zimpatch@exe/zimpatch.cpp.o' -c ../src/zimpatch.cpp
../src/zimpatch.cpp: In function ‘void create(const string&, const string&, const string&)’:
../src/zimpatch.cpp:67:14: error: ‘class zim::writer::Creator’ has no member named ‘configMinClusterSize’; did you mean ‘configClusterSize’?
   67 |   zimCreator.configMinClusterSize(2048);
      |              ^~~~~~~~~~~~~~~~~~~~
      |              configClusterSize
[4/22] Compiling C++ object 'src/25a6634@@zimpatch@exe/tools.cpp.o'.
ninja: build stopped: subcommand failed.
```

**Comment by kelson42** [comment]
@holta The problem 1 is probably because you don't have the proper version of Mustache, you have solved the problem by yourself. The second problem is because you use a dev version of both libzim and zim-tools (and they don't compile for the moment together)? Do I'm right?

**Comment by holta** [comment]
> problem 1 is probably because you don't have the proper version of Mustache, you have solved the problem by yourself.

What version of Mustache should I be installing?

Did I miss instructions at https://github.com/openzim/zim-tools or some similar place?

> The second problem is because you use a dev version of both libzim and zim-tools (and they don't compile for the moment together)? Do I'm right?

I'm very confused as this worked a week ago:

```
git clone https://github.com/openzim/libzim
cd libzim
meson . build
ninja -C build

cd ..

git clone https://github.com/openzim/zim-tools
cd zim-tools
meson . build
ninja -C build
```

Can you recommend any other way to install a recent version [zimdump](https://openzim.org/wiki/Zimdump) ?

Is it true that Ubuntu 21.10 and/or 21.04 (might!) allow these tools to be installed far more easily?

**Comment by kelson42** [comment]
@holta I think this ismthe version 4.1. There is a ticket somewhere to check the version. For the rest, use released versions, both binaries or sources.

**Comment by kelson42** [comment]
@mgautierfr Code has to be fixed here.

**Comment by holta** [comment]
> @holta I think this ismthe version 4.1.

FYI both versions of [mustache.hpp](https://github.com/kainjow/Mustache/blob/master/mustache.hpp) work when I download (either file) into `/usr/include`:

- Mustache 4.1 (i.e. latest official release from 13 months ago, 2020-04-18)
- master branch of Mustache (i.e. 5-week-old modification to mustache.hpp from 2021-04-11)

(Perhaps revise https://github.com/openzim/zim-tools/blob/master/README.md to mention Mustache, and explain how best to install this new prereq?)

> For the rest, use released versions, both binaries or sources.

Does anybody know if there's a binary version of zim-tools' [zimdump](https://openzim.org/wiki/Zimdump) available anywhere?

(Even if from many months ago?)

**Comment by mgautierfr** [comment]
We had the mustache dependency with the PR #206 and we forgot to update the readme.

> Does anybody know if there's a binary version of zim-tools' zimdump available anywhere?

https://download.openzim.org/release/zim-tools/ and https://download.openzim.org/nightly/2021-05-12/

**Comment by mgautierfr** [comment]
> Can you recommend any other way to install a recent version of zimdump ?

You can use kiwix-build which will build every thing for you (including downloading mustache)
